auctions/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('add_comment/<str:title>/', views.add_comment, name='add_comment'),
    path('delete_comment/<str:title>/', views.delete_watchlist, name='delete_watchlist'), 
    path('add_watchlist/<str:title>/', views.add_watchlist, name='add_watchlist'),
    path('listing/toggle_activation/<str:title>/', views.close_listing_view, name='toggle_listing_activation'),
    path('bid/<str:title>/', views.bid, name='bid'),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
    path('category/', views.category, name='category'),        # Add a slash at the end
    path('category/<str:category>/', views.category_view, name='category_view'),
    path('product/<str:title>/', views.product_view, name='product_view'),
    path("watchlist", views.watchlist_view, name="watchlist"),
    path("creatlisting", views.creatlisting, name="creatlisting")
]

commerce/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf import settings
from django.conf.urls.static import static

# Define urlpatterns first
urlpatterns = [
    path("admin", admin.site.urls),
    path("", include("auctions.urls"))
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

auctions/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils import timezone

class User(AbstractUser):
    GENDER_CHOICES = [
        ('m', 'Masculin'),
        ('f', 'Féminin'),
    ]
    ichoices = [
       ('Phone & Tablet', 'Phone & Tablet'),
        ('Cooking & Culinary Arts', 'Cooking & Culinary Arts'),
        ('Health beauty', 'Health beauty'),
        ('Electronics', 'Electronics'),
        ('Supermarket', 'Supermarket'),
        ('Mode', 'Mode'),
        ('Informatique', 'Informatique'),
        ('Auto & Moto', 'Auto & Moto'),
        ('Home & Office', 'Home & Office'),
        ('Video Games & Consoles', 'Video Games & Consoles'),
        ('Sport stuff', 'Sport stuff'),
        # ... (other choices)
    ]

    telephone = models.CharField(max_length=20)
    city = models.CharField(max_length=100, blank=True, null=True)
    date_b = models.DateField(blank=True, null=True)
    interests = models.CharField(max_length=80, choices=ichoices, blank=True, null=True)
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES, blank=True, null=True)
    def __str__(self):
        return self.username

class Interest(models.Model):
    interest = models.CharField(primary_key=True, max_length=500, choices=[
        ('Phone & Tablet', 'Phone & Tablet'),
        ('Cooking & Culinary Arts', 'Cooking & Culinary Arts'),
        ('Health beauty', 'Health beauty'),
        ('Electronics', 'Electronics'),
        ('Supermarket', 'Supermarket'),
        ('Mode', 'Mode'),
        ('Informatique', 'Informatique'),
        ('Auto & Moto', 'Auto & Moto'),
        ('Home & Office', 'Home & Office'),
        ('Video Games & Consoles', 'Video Games & Consoles'),
        ('Sport stuff', 'Sport stuff'),
    ])

    def __str__(self):
        return self.interest

class Listing(models.Model):
    i_choices = [
        ('Phone & Tablet', 'Phone & Tablet'),
        ('Cooking & Culinary Arts', 'Cooking & Culinary Arts'),
        ('Health beauty', 'Health beauty'),
        ('Electronics', 'Electronics'),
        ('Supermarket', 'Supermarket'),
        ('Mode', 'Mode'),
        ('Informatique', 'Informatique'),
        ('Auto & Moto', 'Auto & Moto'),
        ('Home & Office', 'Home & Office'),
        ('Video Games & Consoles', 'Video Games & Consoles'),
        ('Sport stuff', 'Sport stuff'),
    ]
    
    price = models.CharField(max_length=20, null=True)
    user_f = models.ForeignKey(User, on_delete=models.CASCADE, related_name='listings')
    title = models.CharField(max_length=150, primary_key=True, unique=True, blank=True )
    description = models.CharField(max_length=300)
    num_bids = models.IntegerField(default=0)
    image = models.ImageField(upload_to='images/')
    interests = models.CharField(max_length=80, choices=i_choices, blank=True, null=True)
    active = models.BooleanField(default=True)
    winner = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True, related_name='won_listings')

    def close_listing(self):
        self.active = False
        highest_bid = Bid.objects.filter(listing=self).order_by('-bid_amount').first()
        if highest_bid:
            self.winner = highest_bid.user
            self.save()

    def active_listing(self):
        self.active = True
        self.save()

    def delete(self, *args, **kwargs):
        self.num_bids -= 1
        self.save()
        super(Listing, self).delete(*args, **kwargs)

class Comment(models.Model):
    comment_id = models.AutoField(primary_key=True)
    listing = models.ForeignKey(Listing, on_delete=models.CASCADE, related_name='comments', null=True, blank=True)
    comment = models.CharField(max_length=50)
    comment_time = models.DateTimeField(default=timezone.now, editable=False)

class Bid(models.Model):
    listing = models.ForeignKey(Listing, on_delete=models.CASCADE, related_name='bids', null=True, blank=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    bid_amount = models.DecimalField(max_digits=10, decimal_places=2)
    title = models.CharField(max_length=150, null=True, blank=True)
    bid_time = models.DateTimeField(default=timezone.now, editable=False)

    def save(self, *args, **kwargs):
        is_new_bid = self.pk is None
        super(Bid, self).save(*args, **kwargs)
        if is_new_bid:
            self.listing.num_bids += 1
            self.listing.save()

    def delete(self, *args, **kwargs):
        self.listing.num_bids -= 1
        self.listing.save()
        super(Bid, self).delete(*args, **kwargs)



class Watchlist(models.Model):
    watchlist_id = models.AutoField(primary_key=True)
    listing = models.ForeignKey(Listing, on_delete=models.CASCADE, related_name='watchlist', null=True, blank=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)

auctions/views.py
from django.contrib.auth import authenticate, login, logout
from django.db import IntegrityError
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.http import QueryDict
from django.contrib.auth import login


from django.db import IntegrityError
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from .models import User,Listing,Interest,Comment
from django.shortcuts import render, get_object_or_404, redirect
from .models import User
from django.db.models import Count
from .models import Listing,Watchlist
from django.utils import timezone
from django.contrib.auth.decorators import login_required


def index(request):
    # Define the criteria for active listings
    listings = Listing.objects.filter(active=True)
    all_listings = Listing.objects.all()  # Assuming you have an 'active' field

    # Annotate the number of bids for each active listing
    return render(request, 'auctions/index.html', {'active_listings': all_listings})


    


def listing_detail(request, listing_id):
    listing = get_object_or_404(Listing, pk=listing_id)
    return render(request, 'index.html', {'listing': listing})



def login_view(request):
    
    if request.method == "POST":
        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("index"))
        else:
            return render(request, "auctions/login.html", {
                "message": "Invalid username and/or password."
            })
    else:
        return render(request, "auctions/login.html")


def logout_view(request):
    logout(request)
    return redirect('login')



def register(request):
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]
        telephone = request.POST["telephone"]
        city = request.POST["city"]
        interests = request.POST.getlist('interests')
        gender = request.POST.getlist('gender')      
        date_b = request.POST.get('date_b', None)

        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(request, "auctions/register.html", {
                "message": "Passwords must match."
            })

        # Attempt to create a new user
        try:
            user = User.objects.create_user(
                username=username,
                email=email,
                telephone=telephone,
                city=city,
                interests=','.join(interests),
                gender=','.join(gender),
                date_b=date_b,
                password=password,
            )
            user.save()  # Call save() on the instance, not the model class
        except IntegrityError:
            return render(request, "auctions/register.html", {
                "message": "Username already taken."
            })
        login(request, user)
        return HttpResponseRedirect(reverse("index"))
    else:
        return render(request, "auctions/register.html")
    

def category(request):
    categories = Interest.objects.all()
    return render(request, 'auctions/category.html', {'categories': categories})


def category_view(request, category):
    # Retrieve listings for the specified category
    listings = Listing.objects.filter(interests=category)
    print(listings)
    return render(request, 'auctions/category_view.html',{'listings': listings})

def watchlist(request):
    return render(request, "auctions/watchlist.html")

from django.contrib.auth.decorators import login_required
from .models import User
@login_required

def creatlisting(request):
    missing_fields = []
    if request.method == "POST":
        user = request.user
        title = request.POST.get("title")
        description = request.POST.get("description")
        num_bids  = 0
        interests = request.POST.getlist("interest")
        price = request.POST.get("price")
        image = request.FILES.get('image')
        print(f"Title: {title}")
        print(f"Description: {description}")
        print(f" num_bids : { num_bids }")
        print(f"Price: {price}")
        print(f"Interests: {interests}")
        print(f"Image: {image}")
        print(f"user_f: {user}")
        # Attempt to create a new user
        if not title:
            missing_fields.append("Title")
        if not description:
            missing_fields.append("Description")
        if not price:
            missing_fields.append("Price")
        if not interests:
            missing_fields.append("Interests")
        if not image:
            missing_fields.append("Image")
        
        if missing_fields:
            return render(request, "auctions/creatlisting.html", {
                "message": f"Missing or invalid fields: {', '.join(missing_fields)}"
            })
        try:
            listing = Listing.objects.create(
                user_f=user,
                title=title,
                description=description,
                num_bids = num_bids ,
                price=price,
                interests=','.join(interests),
                image=image,
            )
            listing.save()
            return redirect('index')  # Call save() on the instance, not the model class
        except IntegrityError as e:
            print(f"IntegrityError: {e}")
            return render(request, "auctions/index.html", {
                "messages": "Listing valid."
            })
            
        return render(request, "auctions/index.html", {
                "message": "Listing successfully added "
            })    
    else:
        return render(request, "auctions/creatlisting.html")
    




from django.http import Http404

from django.shortcuts import render, get_object_or_404
from .models import Listing, Comment

from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, render
from .models import Listing,Watchlist


from django.shortcuts import get_object_or_404, render
from .models import Listing

from django.contrib.auth.models import AnonymousUser

def product_view(request, title):
    listing = get_object_or_404(Listing, title=title)
    comments = listing.comments.all()

    # Check if the user is logged in
    if request.user.is_authenticated:
        # User is logged in
        var = Watchlist.objects.filter(user=request.user, listing=listing).exists()
    else:
        # User is not logged in (AnonymousUser)
        var = False  # You can set var to False or handle it differently

    return render(request, 'auctions/product_view.html', {'listing': listing, 'var': var, 'comments': comments})


from django.contrib import messages
from datetime import datetime
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, HttpResponseBadRequest
from .models import Listing, Bid
from django.urls import reverse
from django.shortcuts import redirect

from django.http import HttpResponseBadRequest

from django.http import HttpResponseBadRequest

def bid(request, title):
    listing = get_object_or_404(Listing, title=title)
    current_datetime = timezone.now()

    if request.method == 'POST':
        user = request.user
        bid_amount = request.POST.get('bid_amount')

        if bid_amount is not None:
            try:
                bid_amount = float(bid_amount)
            except ValueError:
                return HttpResponseBadRequest("Invalid bid amount format")

            # Check if the new bid is higher than the current highest bid
            highest_bid = Bid.objects.filter(listing=listing).order_by('-bid_amount').first()
            if highest_bid and bid_amount <= highest_bid.bid_amount:
                return HttpResponseBadRequest("Your bid must be higher than the current highest bid.")
            
            # Create a new bid
            bid = Bid(listing=listing, user=user, bid_amount=bid_amount, bid_time=current_datetime)
            listing.save()
            bid.save()

        # Use the PRG pattern - redirect to the bid page to prevent resubmission
        return redirect('bid', title=listing.title)

    # Handle GET requests here (e.g., initial page load)
    bids = Bid.objects.filter(listing=listing).order_by('-bid_amount')  # Get all bids for the listing
    return render(request, 'auctions/bid.html', {'listing': listing, 'bids': bids})



from django.shortcuts import render, redirect
from .models import Listing

from django.http import HttpResponseForbidden



@login_required
def close_listing_view(request, title):
    listing = get_object_or_404(Listing, title=title)

    # Check if the listing meets your closing condition (e.g., when a certain time has passed)
    # You can add your own condition here
    if listing.close_listing:
        listing.close_listing()
    

        # The listing is closed, and the winner is set
        return HttpResponse("Listing closed successfully. The winner is: " + listing.winner.username)
    else:
        return HttpResponse("The listing is not eligible to be closed yet.")



from django.contrib.auth.models import User
from django.shortcuts import get_object_or_404

from django.shortcuts import redirect, get_object_or_404
from .models import Listing, Comment
from django.shortcuts import get_object_or_404, redirect
from django.shortcuts import get_object_or_404, redirect
from .models import Listing, Comment
from django.contrib.auth.models import User  # Import User model

from auctions.models import User  # Import your custom User model

auctions/templates/auctions/bid.html
{% extends "auctions/layout.html" %}

{% block body %}
<div class="div">
    <style>
        .div {
            color: white;
        }
        .red-text {
            color: black;
        }
        .product-card {
            width: 30%;
            margin: 1%;
            display: inline-block;
            vertical-align: top;
        }
    </style>

    <h2>Active Listings</h2>
    <a class="btn btn-light" style="position: relative; top:-117px; left:0px;" href="{% url 'index' %}">Active Listings</a>
    {% if messages %}
        <div>{{ messages }}</div>
    {% endif %}
    <h1>Bids for {{ listing.title }}</h1>
    <table class="table table-striped">
        <thead>
            <tr>
                <th style="color: red;">User</th>
                <th style="color: red;">Bid Amount</th>
                <th style="color: red;">Bid Time</th>
            </tr>
        </thead>
        <tbody>
            {% for bid in bids %}
            <tr>
                <td style="color: red;">{{ bid.user.username }}</td>
                <td style="color: red;">{{ bid.bid_amount }}</li></td>
                <td style="color: red;">{{ bid.bid_time }}</td>
                
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

auctions/templates/auctions/category.html
{% extends "auctions/layout.html" %}

{% block body %}
<div class="div">
    <style>
        .div {
            color: white;
        }
    </style>

    <h2>Category</h2>
    <a class="btn btn-warning" style="position: relative; top:-117px ; left:88px;margin-right: 10px;" href="{% url 'category' %}">Category</a>
        <table class="table table-hover" style="border: 0; border-collapse: collapse;">
            <thead>
                <tr>
                </tr>
            </thead>
            <tbody>
                {% for category in categories %}
                    <td style="border: none; color: red;">
                    <a  href="{% url 'category_view' category.interest %}">{{ category.interest }}</a>
                    </td>
                {% endfor %}

            </tbody>
        </table>
</div>
{% endblock %}

auctions/templates/auctions/category_view.html
{% extends "auctions/layout.html" %}

{% block body %}
<div class="div">
    <style>
        .div {
            color: white;
        }
        .red-text {
            color: black;
        }
        .product-card {
            width: 30%;
            margin: 1%;
            display: inline-block;
            vertical-align: top;
        }
    </style>

    <h2>Active Listings</h2>
    <a class="btn btn-light" style="position: relative; top:-117px; left:0px;" href="{% url 'index' %}">Listings</a>
    {% if messages %}
        <div>{{ messages }}</div>
    {% endif %}

    <div class="row">
        {% for listing in listings %}  {# Use active_listings queryset #}
            <div class="product-card card">
                <img class="card-img-top img-fluid" src="{{ listing.image.url }}" alt="{{ listing.title }} Image">
                <div class="card-body red-text">
                    <h5 class="card-title red-text">Title: {{ listing.title }}</h5>
                    <p class="card-text">Description: {{ listing.description }}</p>
                </div>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item red-text">Price: {{ listing.price }}</li>
                    <li class="list-group-item red-text">Bids: {{ listing.num_bids}}</li>  {# Use listing.num_bids to access the annotation #}
                    <li class="list-group-item red-text">Interest: {{ listing.get_interests_display }}</li>
                </ul>
                <div class="card-body">
                    <a href="{% url 'product_view' listing.title %}" class="card-link" style="color: green; position: relative; left: 150px;">View product</a>
                                </div>
            </div>
        {% endfor %}
    </div>
    
</div>
{% endblock %}

auctions/templates/auctions/index.html
{% extends "auctions/layout.html" %}

{% block body %}
<div class="div">
    <style>
        .div {
            color: white;
        }
        .red-text {
            color: black;
        }
        .product-card {
            width: 30%;
            margin: 1%;
            display: inline-block;
            vertical-align: top;
        }
    </style>

    <h2>Active Listings</h2>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <a class="btn btn-light" style="position: relative; top:-117px; left:0px;" href="{% url 'index' %}">Listings</a>
    {% if messages %}
        <div>{{ messages }}</div>
    {% endif %}
    <script>
        // Reload the page every 5 seconds (5000 milliseconds)
        setInterval(function() {
            location.reload();
        }, 5000);  // 5000 milliseconds = 5 seconds
    </script>

    <div class="row" >
        {% for listing in active_listings %}  {# Use active_listings queryset #}
        <a href="{% url 'product_view'  listing.title %}">
            <div class="product-card card">
                <a href="{% url 'product_view'  listing.title %}"><img class="card-img-top img-fluid" src="{{ listing.image.url }}" alt="{{ listing.title }} Image"></a>
                <div class="card-body red-text">
                    <h5 class="card-title red-text">Title: {{ listing.title }}</h5>
                    <p class="card-text">Description: {{ listing.description }}</p>
                </div>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item red-text">Price: {{ listing.price }} TND</li>

                    <li class="list-group-item red-text">Creator: {{ listing.user_f }}</li>
                    <li class="list-group-item red-text">Bids: {{ listing.num_bids}}</li>  {# Use listing.num_bids to access the annotation #}
                    <li class="list-group-item red-text">Interest: {{ listing.get_interests_display }}</li>
                    {% if listing.active %}
                    <li class="list-group-item red-text" style="color: green;">Active: {{ listing.active }}</li>
                    {% else %}
                    <li class="list-group-item red-text" style="color: red;">Active: {{ listing.active }}</li>
                    {% endif %}
                    <li class="list-group-item red-text">winner: {{ listing.winner }}</li>
                </ul>
                <div class="card-body">
                    <a href="{% url 'product_view'  listing.title %}" class="card-link" style="color: green; position: relative; left: 150px;">View product</a>
                                </div>
            </div></a>{% endfor %}</div></div>
        
    </div></a>
    
</div>
{% endblock %}

auctions/templates/auctions/interest.html
{% extends "auctions/layout.html" %}

{% block body %}<div class="div">
    <style>
        .div{
            color: white; 
         }</style>
    
    <h2>Register</h2>
    <a class="btn btn-secondary" style="position: relative; top:-117px ; left:205px" href="{% url 'interest' %}">Interest</a>
    {% for listing in Listing %}


    
    {%endfor %}

auctions/templates/auctions/product_view.html
{% extends "auctions/layout.html" %}

{% block body %}
<div class="div">
    <style>
        .div {
            color: white;
        }
        .red-text {
            color: black;
        }
        .product-card {
            width: 40%;
            margin: 1%;
            display: inline-block;
            vertical-align: top;
        }
    </style>

    <h2>Active Listing</h2>
    <a class="btn btn-light" style="position: relative; top:-117px; left:px;" href="{% url 'watchlist' %}">Listings</a>
    {% if user.is_authenticated %}
    {% if not var %}
        <form method="POST" action="{% url 'add_watchlist' listing.title %}">
            {% csrf_token %}
              <button style="position: relative; top:-155px; left:1240px;" type="submit"class="btn btn-dark"> Add Watchlist</button>
              <button style="position: relative; top:-155px; left:1238px;" type="submit"class="btn btn-dark" disabled> Delete Watchlist</button>
        </form>
        {% else %}
        <form method="POST" action="{% url 'delete_watchlist' listing.title %}">
            {% csrf_token %}
            <button style="position: relative; top:-155px; left:1240px;" type="submit"class="btn btn-dark" disabled> Add Watchlist</button>
            <button style="position: relative; top:-155px; left:1238px;" type="submit"class="btn btn-dark" > Delete Watchlist</button>
        </form>
        {% endif %}
    {% endif %}
    {% if messages %}
        <div>{{ messages }}</div>
    {% endif %}
    
    <script>
        // Reload the page every 5 seconds (5000 milliseconds)
        setInterval(function() {
            location.reload();
        }, 15000);  // 5000 milliseconds = 5 seconds
    </script>

    <div class="product-card card">
        <img class="card-img-top img-fluid" src="{{ listing.image.url }}" alt="{{ listing.title }} Image">
        <div class="card-body red-text">
            <h5 class="card-title red-text">Title: {{ listing.title }}</h5>
            <p class="card-text">Description: {{ listing.description }}</p>
        </div>
        <ul class="list-group list-group-flush">
            <li class="list-group-item red-text">Price: {{ listing.price }} TND</li>
            <li class="list-group-item red-text">Bids: {{ listing.num_bids }}</li>
            <li class="list-group-item red-text">Interest: {{ listing.get_interests_display }}</li>
            <li class="list-group-item red-text">Active: {{ listing.active }}</li>
            {% if listing.winner %}
                <li class="list-group-item red-text" style="color: red;">Winner: {{ listing.winner }}</li>
            {% endif %}
        </ul>
        <div class="card-body">

            {% if listing.active %}
            <form method="POST" action="{% url 'bid' title=listing.title %}">
                {% csrf_token %}
                <div class="form-group">
                    <label for="bid_amount" style="color: red;">Bid Amount TND</label>
                    <input type="text" name="bid_amount" class="form-control" id="bid_amount" placeholder="Bid Amount TND">
                </div>
                <button type="submit" class="btn btn-block create-account">Confirm Bid</button>
            </form>
            {% else %}
            <div class="form-group">
                <label for="bid_amount" style="color: red;">Bid Amount TND</label>
                <input type="text" name="bid_amount" class="form-control" id="bid_amount" placeholder="                                                   Bid non valid                   "   disabled >
            </div>
            <button type="submit" class="btn btn-block create-account">Confirm Bid</button>
            {% endif %}
            {% if user == listing.user_f %}
                <form method="POST" action="{% url 'toggle_listing_activation' listing.title %}">
                    {% csrf_token %}
                    {% if listing.active %}
                    <input style="position: relative; top:-1000px; left:650px;" type="submit"class="btn btn-danger" value="{% if listing.active %}Desactive The Listing{% endif %}">
                    {% endif %}
                </form>
               
            {% endif %}
            
        </div>
        
        <form method="POST" action="{% url 'add_comment' listing.title %}">
            {% csrf_token %}
            <div class="form-floating">
                <textarea name="comment_text" class="form-control" placeholder="Leave a comment here" id="floatingTextarea2" style="height: 100px"></textarea>
                <label for="floatingTextarea2">Comments</label>
              </div>
              <button type="submit" class="btn btn-block create-account">Comment</button>
        </form>
       
        <table class="table-light" style="height: 150%;color: #000; width: 350px; position: relative;">
            <thead>
                <tr>
                    <th>Comment</th>
    
                </tr>
            </thead>
            <tbody>
                {% for comment in comments %}
                    <tr>
                        <td>{{ comment.comment }}</td>
                    </tr>
                {% empty %}
                    <tr>
                        <td colspan="2">No comments available for this product.</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        
    </div>
    
</div>

{% endblock %}

auctions/templates/auctions/watchlist.html
{% extends "auctions/layout.html" %}

{% block body %}
<div class="div">
    <style>
        .div {
            color: white;
        }
        .red-text {
            color: black;
        }
        .product-card {
            width: 30%;
            margin: 1%;
            display: inline-block;
            vertical-align: top;
        }
    </style>

    <h2>Active Listings</h2>
    <a class="btn btn-primary" style="position: relative; top:-116px ; left:188px ;"  href="{% url 'creatlisting' %}"> Watchlist</a>
    {% if messages %}
        <div>{{ messages }}</div>
    {% endif %}
    <script>
        // Reload the page every 5 seconds (5000 milliseconds)
        setInterval(function() {
            location.reload();
        }, 5000);  // 5000 milliseconds = 5 seconds
    </script>

    <div class="row" >
        {% for listing in listings %}  {# Use active_listings queryset #}
        <a href="{% url 'product_view'  listing.title %}">
            <div class="product-card card">
                <a href="{% url 'product_view'  listing.title %}"><img class="card-img-top img-fluid" src="{{ listing.image.url }}" alt="{{ listing.title }} Image"></a>
                <div class="card-body red-text">
                    <h5 class="card-title red-text">Title: {{ listing.title }}</h5>
                    <p class="card-text">Description: {{ listing.description }}</p>
                </div>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item red-text">Price: {{ listing.price }}</li>

                    <li class="list-group-item red-text">Creator: {{ listing.user_f }}</li>
                    <li class="list-group-item red-text">Bids: {{ listing.num_bids}}</li>  {# Use listing.num_bids to access the annotation #}
                    <li class="list-group-item red-text">Interest: {{ listing.get_interests_display }}</li>
                    {% if listing.active %}
                    <li class="list-group-item red-text" style="color: green;">Active: {{ listing.active }}</li>
                    {% else %}
                    <li class="list-group-item red-text" style="color: red;">Active: {{ listing.active }}</li>
                    {% endif %}
                    <li class="list-group-item red-text">winner: {{ listing.winner }}</li>
                </ul>
                <div class="card-body">
                    <a href="{% url 'product_view'  listing.title %}" class="card-link" style="color: green; position: relative; left: 150px;">View product</a>
                                </div>
            </div></a>{% endfor %}</div></div>
        
    </div></a>
    
</div>
{% endblock %}